#!/usr/bin/env python

import requests

data = """
{
    "class": "uk.gov.gchq.gaffer.operation.impl.add.AddElements",
    "validate": true,
    "skipInvalidElements": false,
    "input": [
	{
	    "class": "uk.gov.gchq.gaffer.data.element.Edge",
	    "properties": {
		"count": 1
	    },
	    "group": "ipflow",
	    "source": "10.0.1.6",
	    "destination": "10.0.0.1",
	    "directed": true
	},
	{
	    "class": "uk.gov.gchq.gaffer.data.element.Edge",
	    "properties": {
		"count": 1
	    },
	    "group": "ipflow",
	    "source": "10.0.1.6",
	    "destination": "10.2.91.12",
	    "directed": true
	},
	{
	    "class": "uk.gov.gchq.gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "ip",
	    "vertex": "10.0.1.6"
	},
        {
	    "class": "uk.gov.gchq.gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "ip",
	    "vertex": "10.0.0.1"
	},
        {
	    "class": "uk.gov.gchq.gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "ip",
	    "vertex": "10.2.91.12"
	}
    ]
}
"""

url = "http://localhost:8080/rest/v1/graph/doOperation/add/elements"

response = requests.put(url, data, headers={'content-type':'application/json'})

print "Status:",response.status_code
print response.text

